extends Node


const species = {
	
	
	"lileaf":{
		dt.tgname:"Lileaf",
		dt.tgmodel:"lileaf",
		dt.tgtype:dt.tgsunny,
		dt.tgbase:{
			dt.tghp:8,
			dt.tgatk:6,
			dt.tgdef:6,
			dt.tgluck:8,
			dt.tgskill:6,
			dt.tgspeed:6},
		dt.tbmoves:["pollendust","leafscatter","stunseed","none"],
	},
	"poppianna":{
		dt.tgname:"Poppianna",
		dt.tgmodel:"tempstars/poppianna",
		dt.tgtype:dt.tgsunny,
		dt.tgbase:{
			dt.tghp:10,
			dt.tgatk:8,
			dt.tgdef:8,
			dt.tgluck:10,
			dt.tgskill:8,
			dt.tgspeed:8},
		dt.tbmoves:["pollendust","leafscatter","stunseed","none"],
	},
	"frollop":{
		dt.tgname:"Frollop",
		dt.tgmodel:"tempstars/frollop",
		dt.tgtype:dt.tgstormy,
		dt.tgbase:{
			dt.tghp:8,
			dt.tgatk:6,
			dt.tgdef:8,
			dt.tgluck:6,
			dt.tgskill:6,
			dt.tgspeed:6},
		dt.tbmoves:["highkick","dropkick","splash","none"],
	},
	"gargantoad":{
		dt.tgname:"Gargantoad",
		dt.tgmodel:"tempstars/gargantoad",
		dt.tgtype:dt.tgstormy,
		dt.tgbase:{
			dt.tghp:10,
			dt.tgatk:8,
			dt.tgdef:10,
			dt.tgluck:8,
			dt.tgskill:8,
			dt.tgspeed:8},
		dt.tbmoves:["highkick","dropkick","splash","none"],
	},
	"odduck":{
		dt.tgname:"Odduck",
		dt.tgmodel:"tempstars/odduck",
		dt.tgtype:dt.tgspace,
		dt.tgbase:{
			dt.tghp:8,
			dt.tgatk:6,
			dt.tgdef:6,
			dt.tgluck:6,
			dt.tgskill:8,
			dt.tgspeed:6},
		dt.tbmoves:["spacelazer","swiftsmack","superburst","none"],
	},
	"reducks":{
		dt.tgname:"Reducks",
		dt.tgmodel:"tempstars/reducks",
		dt.tgtype:dt.tgspace,
		dt.tgbase:{
			dt.tghp:10,
			dt.tgatk:8,
			dt.tgdef:8,
			dt.tgluck:8,
			dt.tgskill:10,
			dt.tgspeed:8},
		dt.tbmoves:["spacelazer","swiftsmack","superburst","none"],
	},
	"ritty":{
		dt.tgname:"Ritty",
		dt.tgmodel:"tempstars/ritty",
		dt.tgtype:dt.tgsimple,
		dt.tgbase:{
			dt.tghp:8,
			dt.tgatk:6,
			dt.tgdef:6,
			dt.tgluck:8,
			dt.tgskill:6,
			dt.tgspeed:6},
		dt.tbmoves:["swiftsmack","swishsweep","",""],
	},
	"furtail":{
		dt.tgname:"Furtail",
		dt.tgmodel:"tempstars/furtail",
		dt.tgtype:dt.tgsimple,
		dt.tgbase:{
			dt.tghp:8,
			dt.tgatk:6,
			dt.tgdef:6,
			dt.tgluck:8,
			dt.tgskill:6,
			dt.tgspeed:6},
		dt.tbmoves:["swiftsmack","swishsweep","",""],
	},
	"petweet":{
		dt.tgname:"Petweet",
		dt.tgmodel:"tempstars/petweet",
		dt.tgtype:dt.tgsound,
		dt.tgbase:{
			dt.tghp:8,
			dt.tgatk:6,
			dt.tgdef:6,
			dt.tgluck:8,
			dt.tgskill:6,
			dt.tgspeed:6},
		dt.tbmoves:["","","",""],
	},
	"raucaw":{
		dt.tgname:"Raucaw",
		dt.tgmodel:"tempstars/raucaw",
		dt.tgtype:dt.tgsound,
		dt.tgbase:{
			dt.tghp:8,
			dt.tgatk:6,
			dt.tgdef:6,
			dt.tgluck:8,
			dt.tgskill:6,
			dt.tgspeed:6},
		dt.tbmoves:["","","",""],
	},
	"screagle":{
		dt.tgname:"Screagle",
		dt.tgmodel:"tempstars/screagle",
		dt.tgtype:dt.tgsound,
		dt.tgbase:{
			dt.tghp:8,
			dt.tgatk:6,
			dt.tgdef:6,
			dt.tgluck:8,
			dt.tgskill:6,
			dt.tgspeed:6},
		dt.tbmoves:["","","",""],
	},
	"eggry":{
		dt.tgname:"Eggry",
		dt.tgmodel:"eggry",
		dt.tgtype:dt.tgsunny,
		dt.tgbase:{
			dt.tghp:4,
			dt.tgatk:6,
			dt.tgdef:4,
			dt.tgluck:3,
			dt.tgskill:3,
			dt.tgspeed:7},
		dt.tbmoves:["claw","chomp","hotspit",""],
	},
	"faberious":{
		dt.tgname:"Faberious",
		dt.tgmodel:"tempstars/faberious",
		dt.tgtype:dt.tgsunny,
		dt.tgbase:{
			dt.tghp:8,
			dt.tgatk:6,
			dt.tgdef:6,
			dt.tgluck:8,
			dt.tgskill:6,
			dt.tgspeed:6},
		dt.tbmoves:["claw","chomp","hotspit","eggshelllance"],
	},
	"shleep":{
		dt.tgname:"Shleep",
		dt.tgmodel:"shleep",
		dt.tgtype:dt.tgspecial,
		dt.tgbase:{
			dt.tghp:8,
			dt.tgatk:6,
			dt.tgdef:6,
			dt.tgluck:8,
			dt.tgskill:6,
			dt.tgspeed:6},
		dt.tbmoves:["brainwave","","",""],
	},
	"lunaram":{
		dt.tgname:"Lunaram",
		dt.tgmodel:"tempstars/lunaram",
		dt.tgtype:dt.tgspecial,
		dt.tgbase:{
			dt.tghp:8,
			dt.tgatk:6,
			dt.tgdef:6,
			dt.tgluck:8,
			dt.tgskill:6,
			dt.tgspeed:6},
		dt.tbmoves:["brainwave","","",""],
	},
	"slowcone":{
		dt.tgname:"Slowcone",
		dt.tgmodel:"slocone1",
		dt.tgtype:dt.tgsilly,
		dt.tgbase:{
			dt.tghp:8,
			dt.tgatk:4,
			dt.tgdef:5,
			dt.tgluck:5,
			dt.tgskill:5,
			dt.tgspeed:4},
		dt.tbmoves:["sprinkle","coldone","",""],
	},
	"powaffle":{
		dt.tgname:"Powaffle",
		dt.tgmodel:"tempstars/powaffle",
		dt.tgtype:dt.tgsilly,
		dt.tgbase:{
			dt.tghp:8,
			dt.tgatk:6,
			dt.tgdef:6,
			dt.tgluck:8,
			dt.tgskill:6,
			dt.tgspeed:6},
		dt.tbmoves:["sprinkle","coldone","dropkick",""],
	},
	"riffraft":{
		dt.tgname:"Riffraft",
		dt.tgmodel:"rifraft",
		dt.tgtype:dt.tgsolid,
		dt.tgbase:{
			dt.tghp:8,
			dt.tgatk:6,
			dt.tgdef:7,
			dt.tgluck:5,
			dt.tgskill:4,
			dt.tgspeed:3},
		dt.tbmoves:["splash","splashzone","",""],
	},
	"magnut":{
		dt.tgname:"Magnut",
		dt.tgmodel:"magnut",
		dt.tgtype:dt.tgspace,
		dt.tgbase:{
			dt.tghp:5,
			dt.tgatk:7,
			dt.tgdef:7,
			dt.tgluck:3,
			dt.tgskill:3,
			dt.tgspeed:5},
		dt.tbmoves:["nutshot","chomp","",""],
	},
	"flyder":{
		dt.tgname:"Flyder",
		dt.tgmodel:"flyder",
		dt.tgtype:dt.tgspace,#bugs
		dt.tgbase:{
			dt.tghp:5,
			dt.tgatk:5,
			dt.tgdef:5,
			dt.tgluck:8,
			dt.tgskill:5,
			dt.tgspeed:7},
		dt.tbmoves:["flybite","swiftsmack","",""],
	},
	
}

# Called when the node enters the scene tree for the first time.
func _ready():
	for sp in species:
		species[sp].make_read_only()
	

func getname(spec):
	return species[spec][dt.tgname]

func getstg(spec, tag):
	#verify species and tag pls
	
	#if in tgatk, etc, get tgbase[tag], else...
	if tag in [dt.tghp,dt.tgatk,dt.tgdef,dt.tgspeed,dt.tgluck,dt.tgskill]:
		return species[spec][dt.tgbase][tag]
	
	return species[spec][tag]

#get base stats...

